<a href="https://colab.research.google.com/github/uk-zash/Machine-Learning/blob/main/Python_Stack_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. NumPy’s core object is the ndarray (N-dimensional array). Unlike standard Python lists, NumPy arrays allow you to do math on entire blocks of numbers instantly.


NumPy arrays use vectorization to perform mathematical operations on entire blocks of data instantly without writing a single for loop.

example: numpy_array = np.array([1, 2, 3, 4, 5])


### Why NumPy is Superior for Math

- No Explicit Loops: You write direct mathematical expressions like array * 2 or array1 + array2.

- C-Engine Speed: The iteration happens in optimized, pre-compiled C code under the hood, making it up to 100 times faster on massive datasets.

- Contiguous Memory: NumPy stores raw numbers right next to each other in memory. Standard Python lists store scattered pointers to objects, which slows down your CPU.

- Element-Wise Operations: Operations are automatically applied to every individual element in the block.



-- Vectorization means performing a mathematical operation on an entire array of numbers all at once, rather than looping through each item one by one.



How Vectorization Works Under the Hood
Vectorization skips Python's slow internal machinery using two main core mechanisms:

1. SIMD Hardware Instructions: Modern computer processors have a feature called SIMD (Single Instruction, Multiple Data). NumPy utilizes highly optimized compiled libraries (like BLAS or LAPACK) that talk directly to this hardware. Instead of telling your CPU "multiply this number," it tells the CPU "multiply this entire block of 4, 8, or 16 numbers in a single clock cycle."

2. Eliminating Python Type-Checking Overhead: Because standard Python lists can hold a mix of anything—integers, strings, or even other lists—Python must pause at every single element during a loop to check its data type and look up the correct math operation.NumPy arrays are homogeneous (every single element must be the exact same data type, like 64-bit float). Because the data type is completely predictable, NumPy bypasses all type-checking and safety checks, executing the math at raw hardware speeds


```Here is what happens behind the scenes for both approaches:python# --- WHAT PYTHON DOES (Scalar Loop) ---
# For item 1: Check type -> It's an int -> Multiply -> Store pointer
# For item 2: Check type -> It's an int -> Multiply -> Store pointer
for x in python_list:
    result.append(x * 2)

# --- WHAT NUMPY DOES (Vectorized) ---
# All ints? Yes. CPU, execute SIMD multiplication on this whole block now.
numpy_array * 2```


In [105]:
import numpy as np

In [114]:
# Create a basic 1D array
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [115]:
# Create 2D array

matrix = np.array([[1, 2, 3],
                   [3,4, 5]])
matrix

array([[1, 2, 3],
       [3, 4, 5]])

In [116]:
# Array inspection
vector.shape, matrix.shape

((4,), (2, 3))

In [117]:
# Checkd datatype
vector.dtype, matrix.dtype

(dtype('int64'), dtype('int64'))

In [118]:
# Check size
vector.size, matrix.size

(4, 6)

In [119]:
# Generate Sequence
seq = np.arange(5)
seq

array([0, 1, 2, 3, 4])

In [120]:
#create array filled with zeros
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Machine Learning requires a lot of matrix math and changing the shape of your data

In [121]:
# maths applies to the entire array at once ( element wise )

sales = np.array([10, 20 , 30])

taxed_sales = sales*1.2 # Multiples every number by 1.2 instantly
taxed_sales

array([12., 24., 36.])

In [124]:
# Reshaping : Changing a 1D array to 2D matrix
flat_data = np.arange(12)

matrix_data = flat_data.reshape(3 , 4) # 3 rows , 4 columns
flat_data, matrix_data

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [130]:
# Slicing
matrix = np.array([[10, 20 , 30],
                   [70, 80, 90]])

n = matrix[1, 2] # row 1, columns 2
k = n.item()
k

90

In [132]:
# Extract submatrix
matrix[0:2 , 1:3] # submatrix: rows 0 and 1, columns 1 and 2

array([[20, 30],
       [80, 90]])

In [133]:
# Get entire second columns
matrix[: , 1]

array([20, 80])

You can filter data instantly without if statements by passing a conditional expression directly into the brackets

In [134]:
age = np.array([13, 15 , 30 , 20 , 50])

#step 1: create a boolean mask
mask = age >=18
mask

array([False, False,  True,  True,  True])

In [135]:
# step 2: Feed the mask to the array to filter it
adults = age[mask]
adults

array([30, 20, 50])

In [136]:
# Shortcut
adults = age[age>=18]
adults

array([30, 20, 50])

Numpy can collapse dimension to calculate matrices. We use axis = 0 for columns and axis = 1 for rows

In [138]:
# Aggregation along axis
score = np.array([[10 , 20],
                  [30 , 40]])

score.sum().item()

100

In [139]:
score.sum(axis = 0)

array([40, 60])

In [140]:
score.sum(axis = 1)

array([30, 70])

# Handling Missing Data

Real world datasets are messy, Numpy uses a special floating point value called nan ( Not a number) to represent missing information. Because standard math functions fail if a nan is present. we must use specific 'nan safe' operations

In [149]:
sensor_data = np.array([10.5 , 12.1 , np.nan , 12.3])

# mean
np.mean(sensor_data) # Fails

np.float64(nan)

In [150]:
np.nanmean(sensor_data)

np.float64(11.633333333333335)

In [152]:
# Data Transformation ( Log , Exponent)

np.exp(sensor_data)

array([ 36315.50267425, 179871.86225375,             nan, 219695.98867214])

For Data analytics, we often need to create new columsn based on conditions.

In [153]:
credit_score = np.array([380, 800, 700 , 300])

# Label user instantly without a loop
risk_profile = np.where(credit_score >= 600, "Approved", "Rejected")

print(risk_profile)

['Rejected' 'Approved' 'Approved' 'Rejected']


### Random Data generation and reproducibility

In [155]:
range = np.random.default_rng(seed =42)

matrix = range.random((3 , 3))
matrix

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

### Pandas ( Data Wrangler )

In pandas, 1D array is called a Series and 2D array(table) is a DataFrame

In [ ]:
# 1. Loading and inspecting a data
# Before we model a data, we have to understand what it looks like

In [ ]:
import pandas as pd

# 1. Load Data from a csv file
#df = pd.read_csv("oahsfiouhaw.csv")

# or create a Dataframe from a dictionary
data = {
    'Age': [25, 30, 22, np.nan, 28],
    'Salary': [50000, 65000, 45000, 80000, 52000],
    'Department': ['Sales', 'IT', 'Marketing', 'IT', 'Sales']
}

df = pd.DataFrame(data)
df

In [ ]:
df.head() # Shows the first 5 rows

In [ ]:
df.info() # shows column types and non-null counts

In [ ]:
df.describe() # Shows quick statistics ( mean , min , max) for numeric columns

In [ ]:
# Selecting and Filtering data

age = df['Age']
age

In [ ]:
subset = df[['Age' , "Salary"]]
subset

In [ ]:
# Filter rows based on a condition

high_earners = df[df['Salary'] > 60000]
high_earners

In [ ]:
# Filter with multiple conditions

it_high = df[(df['Salary']> 60000) & (df['Department'] == 'IT')]
it_high

In [ ]:
# Handing Missing Data ( NaN )

df.isna().sum() # How many missing values are in each column

In [ ]:
# Option A: Drop any row that has a missing value
df.clean = df.dropna()
df.clean

In [ ]:
# Fill missing with the average ( mean ) of that column
mean_age = df['Age'].mean()
mean_age

In [ ]:
df['Age'].fillna(mean_age , inplace = True)
df['Age']

In [ ]:
# Creating X and Y ( Prep For ML )

y = df['Salary']
x = df.drop('Salary' , axis = 1)
y , x

# Encoding Categorical Date ( Text to Numbers )

Before modelling, we must convert text columns into mathematical representations. The Standard way to do this in Pandas in One-Hot Encoding. This technique converts a text column into multiple columns 0 and 1



In [ ]:
X_encoded = pd.get_dummies(x, columns = ['Department'] , dtype = int)
X_encoded

In [ ]:
# Group by aggreation

For data analytics, we often need to summarize metrics across different segments. Pandas uses groupby to split your data, apply a statistical function, and combine the results.

In [ ]:
dept_summary = df.groupby('Department')[['Salary' , "Age"]].mean()
dept_summary

In [ ]:
# Feature Engineering ( Creating a new Columns )


Often, raw data isn't enough to train a great model. You need to combine columns to create new features that give the model better predictive context.

In [ ]:
df['Salary_Per_Year_of_age'] = df['Salary'] / df["Age"]
df['Is_Senior'] = df['Age'] > 28
df

### Indexing wiht .loc and .iloc

While standard brackets work fine for basic filtering, Pandas provides explicit tools for precise data selection:

- .loc[]: Selects data by label (column names or index names).

- .iloc[]: Selects data by integer position (exact row/column index numbers, like NumPy).

In [ ]:
df.loc[0:2 , 'Age': 'Department'] # Grab row 0 to 2 and Columns Age and Department

In [ ]:
df.iloc[0:3 , 0:2]

In [ ]:
# Counts
df['Department'].value_counts()

In [ ]:
# 1. Define the complete dataset
data = {
    'Store': ['Downtown', 'Westside', 'Downtown', 'Westside', 'Downtown'],
    'Sales': [100, 150, 200, 120, 180],  # Added mock sales numbers
    'Customers': [50, 40, 65, 42, 48]
}
df = pd.DataFrame(data)

# 2. Apply different mathematical functions to different columns
store_summary = df.groupby('Store').agg({
    'Sales': ['sum', 'mean'], # Total sales and average sale per store
    'Customers': 'max'        # The highest single-day customer count
})

# 3. View the final aggregated table
print(store_summary)

In [ ]:
df = pd.DataFrame({
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['IT', 'IT', 'Sales', 'Sales'],
    'Salary': [80000, 50000, 70000, 40000]
})

# Calculate the department average, but broadcast it back to match original rows
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')

# Calculate the deviation feature for a machine learning model
df['Salary_Deviation'] = df['Salary'] - df['Dept_Avg_Salary']
print(df)
